const QUOTES = [
  "Tiny daily gains compound into interview confidence.",
  "Consistency beats intensity—ship one topic today.",
  "One focused hour now saves panic later.",
  "Momentum > motivation. Start, then flow.",
  "Future you is grateful you showed up today.",
  "A solved problem is progress; an attempted problem is learning.",
  "Streaks are fragile—protect today's.",
  "Study when it's hard; that's the growth rep.",
  "Clarity comes from writing code, not from staring at theory.",
  "Your edge is built in quiet, consistent practice blocks.",
  "Uncertainty means you're exploring the frontier of your skill.",
  "Five calm breaths; now implement the idea you already understand.",
  "One topic well understood beats five skimmed.",
  "Let today's effort lower tomorrow's anxiety.",
  "Stop optimizing your plan—optimize your execution.",
  "Debugging teaches patterns lectures can't.",
  "Ship an incremental improvement to your brain today.",
  "Every compile error is a micro feedback loop—use it.",
  "You're one focused session away from momentum.",
  "Half-finished is still a rep logged.",
  "Learn deeply, not loudly.",
  "Interview calm is built from many small completions.",
  "When stuck, narrate the problem in plain language.",
  "Confusion marks the exact boundary to push.",
  "Tiny wins prevent motivational debt.",
  "Discipline is choosing progress over perfect conditions.",
  "Study now so future you can sleep the night before.",
  "Imperfection practiced beats perfection postponed.",
  "Pattern recognition grows only with varied reps.",
  "Reduce scope until you can ship a result.",
  "It's okay to move slow—just don't stop.",
  "Reading code counts. Understanding it counts more.",
  "Protect deep work like a meeting with your future.",
  "Small sessions stacked beat sporadic marathons.",
  "Commit to the process; outcomes will queue.",
  "Your brain caches—feed it frequent refreshes.",
  "Confusion today is clarity tomorrow if you persist.",
  "Documenting a solution cements the pattern.",
  "You don't need motivation; you need a starting motion.",
  "Refactor your habits like you refactor code: gradually.",
  "Skip drama, keep data: track effort, not emotion.",
  "Time will pass anyway—convert some into skill.",
  "Energy follows engagement—open the editor.",
  "Done is a gateway to better.",
  "Today’s 1% is tomorrow’s comfort zone.",
  "Atomic goals avert overwhelm.",
  "Repetition builds neural indexes for recall.",
  "You can’t optimize what you haven’t built yet.",
  "Be a collector of solved edge cases.",
  "Learning curves feel steepest right before pattern lock-in.",
  "Study is silent transformation.",
  "Future offers are negotiated partly today.",
  "Confusion is a sign you're asking bigger questions.",
  "Return to fundamentals—they amortize everywhere.",
  "Mental friction reduces with warmed-up context.",
  "Take notes your future mind will thank you for.",
  "One more rep now prevents relearning later.",
  "Don't fear slow progress—fear halted progress.",
  "Focus is a scarce resource; invest it, don't leak it.",
  "You are accumulating silent leverage.",
  "Curiosity fuels sustainability.",
  "Translate theory to code as soon as possible.",
  "Ship learning artifacts (notes, snippets, summaries).",
  "If you can teach it, you own it.",
  "Mild discomfort indicates growth temperature is right.",
  "Reviewing yesterday's work accelerates today's depth.",
  "Progress beats pace illusions.",
  "Restarting quickly is a meta skill.",
  "Build recall by spaced resurfacing of topics.",
  "Context switching taxes cognitive bandwidth—batch.",
  "Write the brute force first, then optimize.",
  "Fear shrinks when execution grows.",
  "Partial understanding becomes full through attempts.",
  "Today’s solved bug is tomorrow’s pattern recognition.",
  "Silence notifications; amplify focus.",
  "Momentum loves small, early wins.",
  "You don't rise to the occasion; you fall to your training.",
  "Gather failure data points; they map the path.",
  "Shallow review deceives; deep re-implementation sticks.",
  "Practice transforms 'hard' into 'familiar'.",
  "Trust the compounding; distrust the urge to skip.",
  "Design calm systems; develop calm habits.",
  "Mastery hides in boring consistency.",
  "Subtract distractions before adding hacks.",
  "Review why an approach failed—extract the invariant.",
  "Build skill equity daily.",
  "Clarify requirements—in code and in goals.",
  "Sleep is a force multiplier for retention.",
  "Quality emerges from incremental refinements.",
  "Hard now is easy later.",
  "Close loops—unfinished tasks leak focus.",
  "Refuse zero progress days.",
  "Skill is rented, payment due daily.",
  "Typing is not progress; understanding is.",
  "Context builds faster than it rebuilds—keep the streak.",
  "Be proud of showing up, even scrappily.",
  "Precision beats speed during learning.",
  "Debug your approach, not your worth.",
  "Edge cases sharpen insight.",
  "Keep your cognitive cache warm.",
  "Scale habits before you scale ambitions.",
  "Invest attention where future interviews will probe.",
  "Micro improvements accumulate into macro differentiation.",
  "You're training a future calm confidence.",
  "Stay longer with hard ideas—they reveal layers.",
  "Reps today reduce panic tomorrow.",
  "Consistency compounds quietly, then obviously.",
  "A focused 30 minutes beats distracted hours.",
  "Learning is latency arbitrage—act before pressure spikes.",
  "Treat confusion as a signal, not a stop sign.",
  "Your process is the product during prep.",
  "Collect mental models; they compress complexity.",
  "Keep going—your future self is taking notes.",
];

export function randomQuote() {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}

export function gentleNudge(missedDays: number) {
  if (missedDays <= 0) return null;
  if (missedDays === 1)
    return "You missed yesterday—rebuild the streak with one small win.";
  if (missedDays < 4)
    return `${missedDays} days off—restart with the easiest pending topic.`;
  return "Long gap detected. Reset expectations: 20 focused minutes now.";
}
